### ISSUE TITLE
[FEATURE] Game build version b2944

### ISSUE THREAD

**Issue by AustinTheAngel** [ikt32/GTAVManualTransmission#144]
Hello dear @ikt32,
please add the game build version b2944 to the Gears.asi as early as possible. I would like to use your script on my FiveM server but it wont let me use it, because the Geras.asi file won't work with the game build b2944 (as I have seen it in the F8 console on FiveM).
Thanks for reading and I hope we will get a new update to version b2944 early.

Best regards
- @AustinTheAngel

**Comment by ikt32** [comment]
It's already there, just no release:
https://github.com/ikt32/GTAVManualTransmission/blob/9618fcac98fae0d6e72aacba71fbf898177a8cb5/Gears/Gears.rc#L28
