### ISSUE TITLE
Logitech Wheel not Connecting[BUG]

### ISSUE THREAD

**Issue by ViperZ7** [ikt32/GTAVManualTransmission#145]
**Describe the bug**
In wheel_setup.exe, my wheel is recognised but as soon as i open gta, it says device disconnected

**Expected behavior**
it worked perfectly fine and then i reinstalled the game and now it refuses to work

**Used versions and additional hardware:**

 - Additional hardware: e.g. Logitech G920, Xbox One controller

**Comment by ikt32** [comment]
Re-register the device if ports or drivers have changed. The devices' GUID probably has changed, and MT does not have contextual checks to automatically update the GUID.
