### ISSUE TITLE
[BUG] The steering mechanism doesn't actually turn the car's wheels.

### ISSUE THREAD

**Issue by mouraleonardo** [ikt32/GTAVManualTransmission#146]
**Describe the bug**

- I can steer motorcycles, but I can't steer cars. The steering wheel's animation works inside the car, but the wheels don't actually turn.

**To Reproduce**

- Configure the steering wheel in the menu.
- Get into any car and attempt to turn the wheel.
- Ride a motorbike and attempt to turn the wheel. 

**Expected behavior**

- I'd like to turning the wheel resulting in the front tires moving, or simply that the car is drivable.

**Screenshots and/or videos**
https://youtu.be/QtROQcdGR6w

**Used versions and additional hardware:**
 - Game version: 12915121
 - Mod version: 5.6.1 Current
 - Additional hardware: Fanatec DD Pro

**Comment by ikt32** [comment]
> It's a known issue on build 3095 and I do not have time to fix it.
