### ISSUE TITLE
NOT WORKING FOR CURRENT UPDATE - PLEASE FIX

### ISSUE THREAD

**Issue by jareddddddd** [ikt32/GTAVManualTransmission#147]
While the mod recognizes the steering wheel and pedals, and the menu acknowledges the wheel's input, the car's wheels in-game do not respond to the steering wheel's movements. However, you still receive feedback through the steering wheel when driving. Essentially, the steering wheel's input is not translating into in-game vehicle control.

**Comment by ikt32** [comment]
Don't abuse issues to whine.
