### ISSUE TITLE
Build 3095 compatibility

### ISSUE THREAD

**Issue by ikt32** [ikt32/GTAVManualTransmission#148]
**Describe the bug**
Multiple patches and pattern searches fail on b3095 due to extensive code changes by Rockstar.

**To Reproduce**

* Attempt to run any current Manual Transmission version on GTA V build 3095

**Expected behavior**

No issues.

**Additional context**

I don't have time to look into this. Since Rockstar introduced a manual transmission mode in a drag race, I suspect my whole way of patching out the shifting logic won't do anymore. At the same time, there are natives available to do the shifting, so the whole manual transmission part should probably be rewritten to be fully compatible with b3095+.

**Comment by zikehalil3535** [comment]
We need an update sir, we waiting for.

**Comment by rolandwellinger** [comment]
I can also confirm that manual h-shifting and steering do not work anymore. i really hate rockstar patching such stuff for an old game people want to enjoy with mods. H-Shifting is not so importand but the wheel turning the front wheels is :). So its like written above. Steering Wheel is turning and force feedback is working. But the tires/wheels of the car do not react to the input. Im ready to donate and honorate a fix for this.

**Comment by metoxys** [comment]
_At least_ the following memory adresses in VExt no longer work: Throttle, Brake, Steering, SteeringAngleInput

**Comment by Kzk24** [comment]
Please update this, it's the only mod for gta v 3095 not working and down grading doesn't work. I even tried a pirated copy no mods were working on that either.
Please update this I'm sure the effort you put into telling people you are busy could be used for this my guy... I would even donate bro.

**Comment by ikt32** [comment]
@metoxys 
Can you attach `Gears.log` to a reply? I'm curious of what it all broke.

**Comment by metoxys** [comment]
> @metoxys Can you attach `Gears.log` to a reply? I'm curious of what it all broke.

I diagnosed this by looking at my ghostreplay output (unexpected `0.0`) which also uses VExt, but fingaweg also followed through

**Comment by Kzk24** [comment]
only steering isnt working

**Comment by rolandwellinger** [comment]
@Kzk24 manual shifting is also effected. because maybe of the detach of the clutch and or shift-inputs.

**Comment by Kzk24** [comment]
imagine being the guy that will go online to personally tell you no I'm not going to fix it. Find some rope

**Comment by anotherkzk12MOFO** [comment]
the amount of energy in banning me could have been used for something better
I want something badly its christmas
I even said Id donate
**_I'm not the only one asking for support guy_**/ also all other sources of game configs or back up files have been removed due to the update of rage hook and script hook. I cant code but im using C/c+ to examine the files as I at least know how to manually remove the reticle in 3095.
But I cant understand your code
let alone an ASI thats been compiled
Only Steering doesnt work, gear shifting works fine

**Comment by anotherkzk12MOFO** [comment]
https://forums.gta5-mods.com/topic/43310/can-t-steer-or-control-any-car-or-truck-after-scripthook-gta-v-update-v1-0-3095/11

here are people patiently awaiting your update...
of the STEERING

**Comment by dudeidf4rent** [comment]
wow this man is the most useful human alive. It is not fair that we must claim the same genome when you are clearly the catastrophe.
I just want you to update steering bro
Keep banning me but We will ask and ask and ask
your internet credit is in the shitter
EVERY YOUTUBE VIDEO EVER ABOUT YOUR MOD IS WORTHLESS NOW
NO ONE CAN DOWNGRADE ANYMORE

go find some rope bro ill cash app you

**Comment by dudeidf4rent** [comment]
just use x360ce hopefully this guy goes and kills him self fucking bitch

**Comment by JumbleBumble** [comment]
This is just sad. This is a FREE mod that the author sacrificed their own time making for FREE and here is a bunch of people acting entitled. Either make one yourself, downgrade your GTA or wait patiently as complaining is most likely just going to make them less motivated to update it.

**Comment by goFurselfHeresaRope** [comment]
just stop breathing. I offered to pay you Loser^^^^^^
now i just want you off my planet

**Comment by goFurselfHeresaRope** [comment]
extra go F your self telling me that crap. The maker said "not touching it go downgrade your game"
which isnt possible
defend him all you want MOD STILL DOESNT WORK
LITERALLY ONLY NEEDS STERERING UPDATE AND HE DONT WANT TEACH US HOW TO DO IT OUR SELVES
HE DONT WANT THE DONATION
as far as I can tell he is a worthless idiot and im ashamed to share a species with him

**Comment by JumbleBumble** [comment]
My game is downgraded, so it is indeed possible. Stop acting like a entitled child is my only & last advice for you.

**Comment by ikt32** [comment]
Try to keep discussion on-topic.

**Comment by RusLanParty** [comment]
I would gladly volunteer to fix the issue, but I don't have much experience with memory tinkering. Can you explain to me in more detail what should be done? 
If I understood correctly your way of patching the memory doesn't work anymore, and instead of memory patching we now have to find a way to rewrite the whole thing using native functions?

**Comment by kagikn** [comment]
@RusLanParty In short, the script needs other memory patterns for b3095 or later so it can change how vehicle gears behave (assembly code issues) and transmission data that aren't accessible via native functions (the latter is being addressed in #153).

> > @metoxys Can you attach `Gears.log` to a reply? I'm curious of what it all broke.
> 
> ```
> [ ERROR ] [Patch] Test: [Gears: Shift Up] not found
> [ ERROR ] [Patch] Test: [Gears: Shift Down] not found
> [ ERROR ] [Patch] Test: [Gears: Clutch Rev lim] not found
> [ ERROR ] [Patch] Test: [Gears: Throttle lift] not found
> [ ERROR ] [Patch] Test: [Steer: Steering input] not found
> [ ERROR ] Patchability test failed!
> ```
Without addressing the issues @fingaweg reported (the one above quoted), the script can't change how vehicle gears behave by patching some piece of assembly code about how gear stuff works in GTA5.exe on the fly.

**Comment by rolandwellinger** [comment]
Chill people. Let the pals do they work. Relax. I will try a workarround today by mixing the MOD with the native steering input via X-Box EMU. Will report later on. In the meantime good look with this. Sadly i cannot really help, cause i don't understand how thos asi stuff works at all. It's always magic for me what you guyes are doing. Still ready for honorate very effort. Let me know where i can donate. Mery XMAS.

**Comment by rolandwellinger** [comment]
So here im again. I did a workarround with mixing my existing X360emu setup into it. For introduction. I use a very complex Joystick Mix Setup as you can see here:
https://youtu.be/DFvKCnewfLQ

The Goal there was and ist to support my rotating "Revolver" Seat for GTA5. As you see i can ride all kind of vehicles. In terms of cars i always used the MOD here. And i needed no mapping to X360emu. For all the other stuff i mix various controllers via JoystickGremlin into one X360emu profile.

What i now did is to map the steering axis of my G27 also to the x360emu wich results in a mix between the MOD and the x360 Input. Forcefeedback and aninmation of steering wheel ist from the MOD and the command to the wheels is done by x360. It mixes good together and works at the same time. So driving feels very good. You can also ajust the curve in JoyStickGremin to your preference. Maybe the one or other gets inspired to use a workarround while waiting for the mod.

You can see a short video of my workarround here:
https://youtu.be/rL32AtGPlVs

**Comment by Gtithubin** [comment]
> **Describe the bug** Multiple patches and pattern searches fail on b3095 due to extensive code changes by Rockstar.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> * Attempt to run any current Manual Transmission version on GTA V build 3095
> 
> **Expected behavior**
> 
> No issues.
> 
> **Additional context**
> 
> I don't have time to look into this. Since Rockstar introduced a manual transmission mode in a drag race, I suspect my whole way of patching out the shifting logic won't do anymore. At the same time, there are natives available to do the shifting, so the whole manual transmission part should probably be rewritten to be fully compatible with b3095+.

**Bug** 
Force feedback for my wheel doesn't work at all, even after downgrading the update.rpf , update2.rpf, GTA5.exe , PlayGTAV.exe and deleted the new dlcpacks introduced with the new update.

**To Reproduce**
* Game updates to newest version, downgrade to version 2802, drive around and feel no force feedback in the wheel.

**Expected behavior**
In version 2802, feel force feedback in wheel.

**Additional context**
The mod is trying to output force feedback as I have the force feedback bar that shows it, but nothing outputs to my wheel, steering does work, and even assigned buttons on the wheel work, but the force feedback is gone. 
I've tried to config force feedback inside the mod and many other settings but nothing seems to work, maybe there's a new file that I don't know about that needs downgrading.

**Comment by rolandwellinger** [comment]
@Gtithubin Thats very interesting, because Forcefeedback and the Steering-Wheel is working on my side. The only thing is that the output to the wheels and the manual shift isn't working.

**Comment by GttMone** [comment]
# ManualTransmission Workaround Without Downgrading GTA V
For those not wanting or not being able to downgrade GTA V, you can download FiveM and host a server locally. You can follow [the official guide](https://docs.fivem.net/docs/server-manual/setting-up-a-server-txadmin/). There are also plenty of tutorials out there (just make sure you're not watching some sketchy advertisers that promote their paid VPS). Also make sure you add the following lines to your server.cfg:
```
sv_enforceGameBuild 2944
sv_scriptHookAllowed 1
```

**Comment by Gale-B** [comment]
### **@ikt32 Your a no good piece of shit cock fuck bottom feeding scum.**

**Comment by ikt32** [comment]
#154 was just merged, fixing the steering override patch.
Still broken are the shift up/shift down patches. Beyond that, gear ratios are wrongly offset.

**Comment by amura87516** [comment]
> #154 was just merged, fixing the steering override patch. Still broken are the shift up/shift down patches. Beyond that, gear ratios are wrongly offset.

[ikt32](https://github.com/ikt32) Can you release a new build version for this update? 🙏

**Comment by Tylerl2j89** [comment]
Give me a week.

**Comment by Rick-Nasher** [comment]
Great if steering with logitech G29 works again, for the Epic version of GTA V can't do a roll back to earlier version, rendering GTA V useless(no fun w/o the Manual Transmission).

**Comment by itsHazeyo** [comment]
if you enable GearboxManual and GearboxDirectShift within a vehicles strAdvancedFlags it will allow you to use rockstars built in manual mode with some down sides but i'm sure that may have something to do with it.

**Comment by Ryan556223** [comment]
How do we find/install the new commit to fix steering? I understand MT and other features dont work but I have seen people have managed to fix the sterring thru the new commit, however I cant find which file to download as they are not in the mod files to replace

**Comment by Ntimm1129** [comment]
> How do we find/install the new commit to fix steering? I understand MT and other features dont work but I have seen people have managed to fix the sterring thru the new commit, however I cant find which file to download as they are not in the mod files to replace

I’m curious about this. I didn’t think there was a way to download a merged commit. Where did you see people doing that?

**Comment by brittz** [comment]
Hi there. You can compile de application by downloading de repository to your pc and installing the programs in the building requirements section **https://github.com/ikt32/GTAVManualTransmission?tab=readme-ov-file#building-requirements**

I already did that, if you want to try.
https://drive.google.com/file/d/13si64L0UjhO_uqva0Hvc2htYfWrAp7S3/view?usp=sharing

**Comment by NokTham** [comment]
New build works on Epic?

**Comment by Unknown9696** [comment]
Where i can download the new version?

**Comment by waynieoaks** [comment]
> Where i can download the new version?

You can compile or download the one @brittz did a few posts up:
https://github.com/ikt32/GTAVManualTransmission/issues/148#issuecomment-1925338828

**Comment by Unknown9696** [comment]
Thank you so much Waynieoaks! Have a nice day!

**Comment by Unknown9696** [comment]
I tested the new version but when it is in Automatic it does not change gears and when it is on Sequential from the 3rd gear it does not work anymore

**Comment by waynieoaks** [comment]
That's strange because the build from @brittz works for me in automatic - steering and auto gears. 

Manual gears is another issue that people are still trying to fix I believe

**Comment by NokTham** [comment]
Yeah, Automatic gears don't seem to work on my end too.
Using the Epic version.

**Comment by tom21342** [comment]
es el mejor mod de gta5 y no lo acutalizan hijos de puta

**Comment by rolandwellinger** [comment]
Thanks all for your effort. I will soon update it on my side. Still using my workarround. Im not playing GTA5 so often.

**Comment by Rick-Nasher** [comment]
Same here, on **Epic version**, with **Logitech G29**+pedals and gears:
No automatic gears, was stuck at 40KM/hr, but the steering at least is fixed, so drivable! 

Weird thing is: before I used the broken one from 5mods, which failed at steering, but gears were working ok!
I opted for the x360CE method for steering, but it was awful, gf couldn't drive it.

I compiled the latest github clone repo, about 2 weeks ago from within VS2022 using: https://github.com/ikt32/GTAVManualTransmission.git
Never compiled C++ since the 90's and never in VS so was bit of a learning curve.  
If anybody needs it (prob not round here 😉 ), I wrote down a few steps, so just ask.

**Comment by daze1msk** [comment]
@Rick-Nasher Does the shifting works or is it still the same as before? 

I'm new here so it would be great if you could guide me :)

**Comment by Rick-Nasher** [comment]
> @Rick-Nasher Does the shifting works or is it still the same as before?
> 
> I'm new here so it would be great if you could guide me :)

Not that new see you were here since 2022! - If not being sarcastic then I'll here from you on discord, for I don't think ikt32 wants this in his thread. 😉

**Comment by daze1msk** [comment]
@Rick-Nasher Been on github since 2022 as im studying computer science haha ;). So you want to contact me through discord?

**Comment by Rick-Nasher** [comment]
> @Rick-Nasher Been on github since 2022 as im studying computer science haha ;). So you want to contact me through discord?

Not a big gamer here so never really use discord, but hey it serves the purpose. Its just a small text, I guess I could expand on it but at least all the info is in one(alsmost) place: https://discord.gg/v7yS3P2z

**Comment by ALamX** [comment]
> Hi there. You can compile de application by downloading de repository to your pc and installing the programs in the building requirements section **https://github.com/ikt32/GTAVManualTransmission?tab=readme-ov-file#building-requirements**
> 
> I already did that, if you want to try. https://drive.google.com/file/d/13si64L0UjhO_uqva0Hvc2htYfWrAp7S3/view?usp=sharing

Any progress on the automatic gears issue on this?
Also
Bump

**Comment by MaverickMartyn** [comment]
Would it be possible to get a build with manual transmission stripped out?
I don't have a shifter atm, so I don't mind fully automatic transmission like vanilla GTA.

**Comment by ikt32** [comment]
There are no plans for such a thing.

**Comment by MaverickMartyn** [comment]
> There are no plans for such a thing.

That's disappointing, but fair. I just got my wheel, and I was excited to give GTA 5 a spin, but I guess I'll have to wait.
I'd love to assist, but I'm a C# guy. I'd have no clue where to even begin.

**Comment by ikt32** [comment]
You can downgrade in the meantime.

I have plans for continuing this, but it's going to involve archiving this repository.

**Comment by ikt32** [comment]
Hi all,
Manual Transmission 5.6.2 resolves the compatibility issues with GTA V 1.0.3095.0 and newer. Unfortunately, it will be available exclusively via [Patreon](https://www.patreon.com/ikt). As such, this issue will be closed and this repository will be archived soon.

Thank you all for your support and comments on this project.
