### ISSUE TITLE
Steering doesnt work, clutch and all else worked just fine

### ISSUE THREAD

**Issue by anotherkzk12MOFO** [ikt32/GTAVManualTransmission#151]
CANNOT DOWNGRADE GAME EVERYONE HAS UPDATED TO 3095 AND ALL GAME CONFIG FILES ARE GONE
CANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADE
JUST SAYING i CANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADECANNOT DOWNGRADE

**Comment by anotherkzk12MOFO** [comment]
LITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADE CRASHES EVERYTIME
LITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADELITERALLY ONL STEERING DOESNT WORK
CANNOT DOWNGRADE

**Comment by anotherkzk12MOFO** [comment]
Jun 1, 2010 — You can't edit C++ script ("asi file"). Once it is compiled, you can't edit or open it. The only way you can edit it is getting the source ( ...

**Comment by ikt32** [comment]
This behavior does not increase the chances of me working on this.
