### ISSUE TITLE
[BUG] Mouse Steering working when disabled.

### ISSUE THREAD

**Issue by lilKaHann** [ikt32/GTAVManualTransmission#156]
I dont know if this might help with the steering not working, and this is about the only way I could think of mentioning it. 

**Describe the bug**
Mouse Steering is on, even when disabled in the settings.

**To Reproduce**
Disable Mouse Steering in settings
hold left mouse button, move left/right

**Expected behavior**
no mouse steering when disabled

**Used versions and additional hardware:**
 - Game version: 3095
 - Mod version: 5.6.1
 - Additional hardware: Logitec g27 wheel

**Comment by ikt32** [comment]
As explained in #148 - compatibility with build 3095 is broken. This means the custom steering solutions and manual transmission parts will not work. Downgrade or submit a PR that fixes the issue, as I'm not actively working on any GTA V projects.
