### ISSUE TITLE
[bug] new gta v update

### ISSUE THREAD

**Issue by 2ky09** [ikt32/GTAVManualTransmission#158]
The car tires does not turn to the right or to the left, but the steering wheel inside the car works normally

**Comment by lilKaHann** [comment]
Since the last gta v update wheel support isn't working, and the author isn't working on it right now because people don't read and just spam post about the steering not working

**Comment by ikt32** [comment]
Hi,

I'm already aware, issue #148 tracks this issue already. As for now I'm not working on this issue. The latest build/commit should have fixed steering thanks to @kagikn , but the manual transmission part is still broken. Downgrade if you want to use the script.
