### ISSUE TITLE
Controlling the car with the mouse

### ISSUE THREAD

**Issue by Bubenchuk** [ikt32/GTAVManualTransmission#161]
Please share the settings to be able to control the car with the mouse so that the mouse sensitivity is minimized. Also interesting to know: how to make the steering wheel turn by 900 degrees.

**Comment by ikt32** [comment]
Controls -> Steering assists -> Mouse steering (You'll probably need the Enhanced steering enabled, which also enables the 900 degree animation stuff).

Since enhanced steering is broken since 3095, please use an older game version.
