### ISSUE TITLE
[BUG] After installing the mod, cars can no longer be turned.

### ISSUE THREAD

**Issue by BATL3R** [ikt32/GTAVManualTransmission#166]
After installing the mod, cars can no longer be turned. It seems like the steering wheel is visually spinning, but the wheels are not physically turning. What to do?

**Comment by Highland-ai** [comment]
I can also confirm this issue.

**Comment by CKAY-9** [comment]
I managed to get steering working with the mod; however, I had to disable the "enhanced steering" in Controls > Steering Assists. Not an optimal fix but I don't mind for an outdated mod.

**Comment by ikt32** [comment]
Duplicate of #148. (Yes, the steering patching is broken, among with other stuff).
