### ISSUE TITLE
help tuning

### ISSUE THREAD

**Issue by chaseq518** [ikt32/GTAVManualTransmission#167]
I am not very sure what else to tune, I’ve tried curves but i don’t know how to get what I want. my steering is too stiff when I want enough feedback to read the car but I want it to not be too heavy to the point where it’s annoying to drive, to be specific i’ve tried lower SAT multiplier in config, and different FFB curves

**Comment by ikt32** [comment]
Make sure your car handling is decently realistic - the [readme](doc/README.md#handling-for-force-feedback) has a few guidelines on which parameters should have approximately which values.

**Comment by Volossya** [comment]
Author, since then you haven’t succeeded in anything. The steering wheel worked.
