### ISSUE TITLE
[FEATURE] Add FX Version to Source Code For Wheel Players On FiveM

### ISSUE THREAD

**Issue by Bohannonaaron** [ikt32/GTAVManualTransmission#168]
**What does this feature relate to?**
Wheel FiveM

**Describe the solution you'd like**
Add the source code

**Comment by ikt32** [comment]
This is already present.

https://github.com/ikt32/GTAVManualTransmission/blob/adb5bdb190c436f2e150eda5dc1fd21570228a60/Gears/Gears.rc#L28
