### ISSUE TITLE
No way to get the latest binary? Releases on the GitHub Releases page are outdated; the files generated in the Actions section are expired and cannot be downloaded.

### ISSUE THREAD

**Issue by randomdavis** [ikt32/GTAVManualTransmission#169]
Basically what the title says; am I missing something here? See the below screenshots, taken just now.

![image](https://github.com/ikt32/GTAVManualTransmission/assets/11844052/16f87cba-183e-4204-9ee9-9e5c5679115d)

![image](https://github.com/ikt32/GTAVManualTransmission/assets/11844052/1c1e44f5-76f0-4cef-b80a-e655c5ee411c)

**Comment by nachitodev** [comment]
https://pipelinesghubeus11.actions.githubusercontent.com/2HZVB6NxXSPYyYAzn0tb4plfAls3SdyBCbturRY8f6XQnU0N8a/_apis/pipelines/1/runs/3/signedartifactscontent?artifactName=Gears-d4f053136501c71ab2a06184fbe10876af2e3994&urlExpires=2024-06-09T22%3A27%3A49.4476777Z&urlSigningMethod=HMACV2&urlSignature=fVXsNhkNsCazzvgG0I71hNZcokRio%2BLl%2F4D%2BsYS9NK0%3D

**Comment by nachitodev** [comment]
https://nightly.link/nachitodev/GTAVManualTransmission/actions/runs/9439901910/Gears-d4f053136501c71ab2a06184fbe10876af2e3994.zip

**Comment by ikt32** [comment]
5.6.1 is the latest official binary, I don't plan on making the nightly builds persistent nor do I want to make a release from the latest changes as those are insufficiently compatible with the latest game updates.

Download binaries from forks or other people's own builds at your own risk.
