### ISSUE TITLE
[FEATURE] It's possible send data to Simhub?

### ISSUE THREAD

**Issue by Betty1909** [ikt32/GTAVManualTransmission#171]
Get car RPM, Km/h, temp, abs, tcs, handbrake, turn signal, gear data and send it into Simhub.

 thank you very much!

**Comment by ikt32** [comment]
This is already available under the UDP telemetry feature, which publishes GTA V data in Codemaster format.

[The implemented values can be seen in the implementation](https://github.com/ikt32/GTAVManualTransmission/blob/master/Gears/UDPTelemetry/UDPTelemetry.cpp)
