### ISSUE TITLE
[BUG] Steering not work

### ISSUE THREAD

**Issue by Betty1909** [ikt32/GTAVManualTransmission#172]
In game car not steering with joystick, but steering wheel icon and in game pov view steering wheel can steering.

**Used versions and additional hardware:**
 - Game version: [e.g. 1.0.1337.1 on Steam)
 - Mod version: 5.6.1
 - Additional hardware: MOZA R12

**Settings, if applicable:**
[settings_general.txt](https://github.com/user-attachments/files/16402955/settings_general.txt)
[settings_wheel.txt](https://github.com/user-attachments/files/16402957/settings_wheel.txt)

**Comment by ikt32** [comment]
Closing as duplicate issue of https://github.com/ikt32/GTAVManualTransmission/issues/148
